# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tGBampuOxOCr0nzw72p4m8PmRRF7zyhg
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as mlp
import seaborn as sb
import sklearn as sk
from google.colab import files
uploaded = files.upload()

datafile = pd.read_csv("Social_Network_Ads.csv")

datafile

